spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/charlyMarket   # DB명: charlyMarket
    username: ADMIN
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10        # 최대 커넥션 개수
      minimum-idle: 5              # 최소 유지 커넥션 수
      idle-timeout: 30000          # idle 커넥션 유지 시간(ms)
      max-lifetime: 1800000        # 커넥션의 최대 수명(ms) - 보통 30분
      connection-timeout: 30000    # 커넥션 풀에서 커넥션 가져올 때 최대 대기 시간(ms)

  jpa:
    hibernate:
      ddl-auto: update             # create, create-drop, update, validate, none 중 선택
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # 성능상 권장 옵션

logging:
  level:
    org.hibernate.SQL: debug       # SQL 로그 확인용
    org.hibernate.type: trace      # 바인딩 파라미터 값까지 확인

server:
  port: 8080                       # 서버 포트
